Default start timeout
avito-tech/aqueduct pull request #42
Opened 2023-03-21 20:32 UTC by cyberlis

Default start timeout in aiohttp integration
Check timeout when try to put value to queue
Fix deadlock on exit when input queue has items

2023-03-21 21:43 UTC, bugrimov commented
Very good idea! 
Lets go throughth my comments and please dont forget to change version and changelog

2023-03-22 08:07 UTC, bugrimov requested changes

2023-03-22 08:35 UTC, cyberlis commented on aqueduct/flow.py
> +            queue.cancel_join_thread()
Yes, because at this point we do not check workers's errors and we don't wait for workers.

2023-03-22 08:37 UTC, cyberlis commented on aqueduct/flow.py
> +        while self.state != FlowState.STOPPED:
The same answer as for `self._state = FlowState.STARTING` line
self.stop will gracefully stop flow and only after that set `self.state` to `FlowState.STOPPED`

2023-03-22 15:26 UTC, merged